//! Cross-language oracle test: this crate's weighted MDR construction
//! (Equation 6.1, `src/selective/evalue_weighted.rs`) against the
//! official `Tian-Bai/SCoRE` Python implementation.
//!
//! Fixture: `tests/fixtures/score_mdr_w_v0_1_1.json`, generated by
//! `scripts/oracles/generate_score_mdr_w.py` against commit
//! `401b7caf6d030825ff67e8f08e44ba15ee8c94af` (package version `0.1.1`,
//! MIT license, copyright Tian Bai and Ying Jin -- see
//! `THIRD_PARTY_NOTICES.md`). Python is never invoked by this test or by
//! `cargo test`; only the committed JSON is read.
//!
//! Two independent comparisons per test point (see the fixture's own
//! `provenance.notes` and `docs/references.md` for why there are two,
//! not one):
//!
//! - `reference_evalues`: the e-value itself, checked with a combined
//!   absolute/relative tolerance, against the fixture generator's own
//!   from-scratch Python breakpoint-enumeration implementation of
//!   Equation 6.1 (not derived from this crate's Rust code, and not from
//!   the official package, which has no weighted e-value function at
//!   all). A value of `"Infinity"` in the fixture means the reference
//!   implementation found the true infimum to be unbounded; this test
//!   requires the Rust side to agree it is exactly
//!   `EValue::PositiveInfinity`, not merely "large".
//! - `official_selected_indices`: the actual deploy/abstain decision from
//!   the official `SCoRE_MDR_w` shortcut, checked exactly for *every*
//!   case. Unlike `SCoRE_MDR`'s unweighted shortcut (which this crate
//!   also never uses, but has not verified against for `gamma > alpha`),
//!   this crate's own `weighted_risk_adjusted_evalue` never takes any
//!   shortcut at all -- it always computes Equation 6.1's actual infimum
//!   -- so its decision does not depend on the shortcut's `gamma > alpha`
//!   overlap condition already agreeing with it; a 300,000-trial
//!   randomized search (see the fixture generator's module docs) found
//!   zero mismatches, including cases where that overlap condition
//!   changes the shortcut's naive decision. `gamma_le_alpha` is still
//!   recorded per case as descriptive metadata, not as a gate on this
//!   comparison.

use risksieve::selective::evalue_weighted::{EValue, weighted_risk_adjusted_evalue};
use risksieve::{ClosedUnitInterval, NonNegative, OpenUnitInterval};
use serde_json::Value;

const FIXTURE: &str = include_str!("fixtures/score_mdr_w_v0_1_1.json");
const ABS_TOL: f64 = 1e-9;
const REL_TOL: f64 = 1e-9;

fn approx_eq(actual: f64, expected: f64) -> bool {
    (actual - expected).abs() <= ABS_TOL.max(REL_TOL * actual.abs().max(expected.abs()))
}

fn as_f64_vec(value: &Value) -> Vec<f64> {
    value
        .as_array()
        .expect("expected a JSON array")
        .iter()
        .map(|entry| entry.as_f64().expect("expected a JSON number"))
        .collect()
}

fn as_usize_vec(value: &Value) -> Vec<usize> {
    value
        .as_array()
        .expect("expected a JSON array")
        .iter()
        .map(|entry| {
            entry
                .as_u64()
                .expect("expected a non-negative JSON integer") as usize
        })
        .collect()
}

/// Parses a `reference_evalues` entry: either a JSON number, the string
/// `"Infinity"`, or `null` (a fully degenerate combined weight, not
/// expected in this fixture but handled for completeness).
fn parse_reference_evalue(value: &Value) -> Option<EValue> {
    if value.is_null() {
        return None;
    }
    if let Some(text) = value.as_str() {
        assert_eq!(
            text, "Infinity",
            "unexpected string reference e-value: {text}"
        );
        return Some(EValue::PositiveInfinity);
    }
    Some(EValue::Finite(
        NonNegative::new(
            "reference_evalue",
            value.as_f64().expect("expected a JSON number"),
        )
        .expect("reference e-value must be non-negative and finite"),
    ))
}

#[test]
fn weighted_evalues_match_reference_and_official_decisions() {
    let fixture: Value = serde_json::from_str(FIXTURE).expect("fixture must be valid JSON");

    let provenance = &fixture["provenance"];
    assert_eq!(
        provenance["repository"].as_str(),
        Some("https://github.com/Tian-Bai/SCoRE")
    );
    assert_eq!(provenance["package_version"].as_str(), Some("0.1.1"));
    assert_eq!(
        provenance["commit_sha"].as_str(),
        Some("401b7caf6d030825ff67e8f08e44ba15ee8c94af")
    );

    let cases = fixture["cases"].as_array().expect("cases must be an array");
    assert!(!cases.is_empty(), "fixture must contain at least one case");

    for case in cases {
        let name = case["name"].as_str().expect("case name");
        let calibration_losses: Vec<ClosedUnitInterval> = as_f64_vec(&case["calibration_losses"])
            .into_iter()
            .map(|value| ClosedUnitInterval::new("loss", value).unwrap())
            .collect();
        let calibration_scores = as_f64_vec(&case["calibration_scores"]);
        let calibration_weights: Vec<NonNegative> = as_f64_vec(&case["calibration_weights"])
            .into_iter()
            .map(|value| NonNegative::new("weight", value).unwrap())
            .collect();
        let test_scores = as_f64_vec(&case["test_scores"]);
        let test_weights: Vec<NonNegative> = as_f64_vec(&case["test_weights"])
            .into_iter()
            .map(|value| NonNegative::new("weight", value).unwrap())
            .collect();
        let alpha = OpenUnitInterval::new("alpha", case["alpha"].as_f64().unwrap()).unwrap();
        let gamma = OpenUnitInterval::new("gamma", case["gamma"].as_f64().unwrap()).unwrap();

        let expected_evalues: Vec<Option<EValue>> = case["reference_evalues"]
            .as_array()
            .expect("reference_evalues must be an array")
            .iter()
            .map(parse_reference_evalue)
            .collect();
        let expected_selected = as_usize_vec(&case["official_selected_indices"]);

        assert_eq!(test_scores.len(), expected_evalues.len(), "case `{name}`");

        let mut actual_selected = Vec::new();
        for (j, (&test_score, &test_weight)) in
            test_scores.iter().zip(test_weights.iter()).enumerate()
        {
            let outcome = weighted_risk_adjusted_evalue(
                &calibration_losses,
                &calibration_scores,
                &calibration_weights,
                test_score,
                test_weight,
                gamma,
            )
            .unwrap_or_else(|err| panic!("case `{name}`, test point {j}: {err:?}"));

            match expected_evalues[j] {
                Some(EValue::PositiveInfinity) => {
                    assert_eq!(
                        outcome.value,
                        EValue::PositiveInfinity,
                        "case `{name}`, test point {j}: expected +infinity, got {:?}",
                        outcome.value
                    );
                }
                Some(EValue::Finite(expected)) => match outcome.value {
                    EValue::Finite(actual) => {
                        assert!(
                            approx_eq(actual.get(), expected.get()),
                            "case `{name}`, test point {j}: e-value mismatch (rust={}, reference={})",
                            actual.get(),
                            expected.get()
                        );
                    }
                    EValue::PositiveInfinity => {
                        panic!(
                            "case `{name}`, test point {j}: rust returned +infinity, reference expected {}",
                            expected.get()
                        );
                    }
                },
                None => {} // degenerate reference value; nothing to compare
            }

            if outcome.value.clears_deployment_threshold(alpha) {
                actual_selected.push(j);
            }
        }

        assert_eq!(
            actual_selected, expected_selected,
            "case `{name}`: selected indices mismatch against the official SCoRE_MDR_w decision"
        );
    }
}
