//! Cross-language oracle test: this crate's coupled SDR construction
//! (Equation 5.1, `src/selective/coupled.rs`) against the official
//! `Tian-Bai/SCoRE` Python implementation's `SCoRE_SDR`.
//!
//! Fixture: `tests/fixtures/score_sdr_v0_1_1.json`, generated by
//! `scripts/oracles/generate_score_sdr.py` against commit
//! `401b7caf6d030825ff67e8f08e44ba15ee8c94af` (package version `0.1.1`,
//! MIT license, copyright Tian Bai and Ying Jin -- see
//! `THIRD_PARTY_NOTICES.md`). Python is never invoked by this test or by
//! `cargo test`; only the committed JSON is read.
//!
//! There is no independent-construction (Equation 4.1) oracle column in
//! this fixture -- see the fixture's own `provenance.notes` and
//! `docs/references.md` for why `SCoRE_MDR_bf` is not used as one.
//!
//! Tolerance: e-values are compared with a combined absolute/relative
//! tolerance (`1e-9` of either kind); selected indices and `tau_hat`
//! require exact equality, per this crate's determinism requirements.

use risksieve::selective::coupled::coupled_risk_adjusted_evalues;
use risksieve::selective::ebh;
use risksieve::{ClosedUnitInterval, OpenUnitInterval};
use serde_json::Value;

const FIXTURE: &str = include_str!("fixtures/score_sdr_v0_1_1.json");
const ABS_TOL: f64 = 1e-9;
const REL_TOL: f64 = 1e-9;

fn approx_eq(actual: f64, expected: f64) -> bool {
    (actual - expected).abs() <= ABS_TOL.max(REL_TOL * actual.abs().max(expected.abs()))
}

fn as_f64_vec(value: &Value) -> Vec<f64> {
    value
        .as_array()
        .expect("expected a JSON array")
        .iter()
        .map(|entry| entry.as_f64().expect("expected a JSON number"))
        .collect()
}

fn as_usize_vec(value: &Value) -> Vec<usize> {
    value
        .as_array()
        .expect("expected a JSON array")
        .iter()
        .map(|entry| {
            entry
                .as_u64()
                .expect("expected a non-negative JSON integer") as usize
        })
        .collect()
}

#[test]
fn coupled_evalues_match_official_score_sdr_oracle() {
    let fixture: Value = serde_json::from_str(FIXTURE).expect("fixture must be valid JSON");

    let provenance = &fixture["provenance"];
    assert_eq!(
        provenance["repository"].as_str(),
        Some("https://github.com/Tian-Bai/SCoRE")
    );
    assert_eq!(provenance["package_version"].as_str(), Some("0.1.1"));
    assert_eq!(
        provenance["commit_sha"].as_str(),
        Some("401b7caf6d030825ff67e8f08e44ba15ee8c94af")
    );

    let cases = fixture["cases"].as_array().expect("cases must be an array");
    assert!(!cases.is_empty(), "fixture must contain at least one case");

    for case in cases {
        let name = case["name"].as_str().expect("case name");
        let calibration_losses: Vec<ClosedUnitInterval> = as_f64_vec(&case["calibration_losses"])
            .into_iter()
            .map(|value| ClosedUnitInterval::new("loss", value).unwrap())
            .collect();
        let calibration_scores = as_f64_vec(&case["calibration_scores"]);
        let test_scores = as_f64_vec(&case["test_scores"]);
        let alpha = OpenUnitInterval::new("alpha", case["alpha"].as_f64().unwrap()).unwrap();
        let gamma = OpenUnitInterval::new("gamma", case["gamma"].as_f64().unwrap()).unwrap();
        let expected_evalues = as_f64_vec(&case["coupled_evalues"]);
        let expected_selected = as_usize_vec(&case["selected_indices"]);
        let expected_tau_hat = case["tau_hat"].as_u64().map(|value| value as usize);

        let actual_evalues = coupled_risk_adjusted_evalues(
            &calibration_losses,
            &calibration_scores,
            &test_scores,
            gamma,
        )
        .unwrap_or_else(|err| panic!("case `{name}` errored: {err:?}"));

        assert_eq!(
            actual_evalues.len(),
            expected_evalues.len(),
            "case `{name}`: e-value count mismatch"
        );
        for (index, (actual, expected)) in actual_evalues
            .iter()
            .zip(expected_evalues.iter())
            .enumerate()
        {
            assert!(
                approx_eq(actual.get(), *expected),
                "case `{name}`: e-value[{index}] mismatch (rust={}, python={})",
                actual.get(),
                expected
            );
        }

        let selection = ebh::select(&actual_evalues, alpha);
        assert_eq!(
            selection.selected_indices, expected_selected,
            "case `{name}`: selected indices mismatch"
        );
        assert_eq!(
            selection.tau_hat, expected_tau_hat,
            "case `{name}`: tau_hat mismatch"
        );
    }
}
